### ISSUE TITLE
irsa module fails to create service account for EKS managed vpc-cni addon

### ISSUE THREAD

**Issue by milosh3411** [aws-samples/aws-eks-accelerator-for-terraform#105]
The error can be reproduced by running example "8-eks-cluster-with-eks-addons" from https://github.com/aws-samples/terraform-ssp-eks-patterns. Service account "aws-node" already exists when irsa_addon module tries to create it for vpc_cni addon:

`Error: serviceaccounts "aws-node" already exists
│
│   with module.aws-eks-accelerator-for-terraform.module.vpc_cni[0].module.irsa_addon.kubernetes_service_account_v1.irsa,
│   on .terraform\modules\aws-eks-accelerator-for-terraform\modules\irsa\main.tf line 32, in resource "kubernetes_service_account_v1" "irsa":
│   32: resource "kubernetes_service_account_v1" "irsa" {`

**Comment by vara-bonthu** [comment]
Thanks @milosh3411 for pointing this issue. VPC CNI gets installed by default while creating EKS Cluster and `aws-node` service account also created by this step. It looks like installing EKS managed vpc-cni add-on is not cleaning up all the existing resources. Terraform may need to reuse the `aws-node` sa in this case to avoid the issue. 
I am looking into the issue will update the issue accordingly.

**Comment by milosh3411** [comment]
Thanks @vara-bonthu 

What happens with "aws-node" service account annotation: "eks.amazonaws.com/role-arn" : aws_iam_role.irsa.arn ?
It seems that existing "aws-node" service account won't be annotated with the created irsa role.

**Comment by vara-bonthu** [comment]
AWS EKS VPC CNI Addon `resource "aws_eks_addon" "vpc_cni"` resource is annotating the IAM role with service account. In this case we don't need to create a new service account since it already exists. 

@milosh3411 You can try the test again with this PR and verify the `aws-node` service account for annotations. Let me know  if you find any issues.

Here is the output from my VPC SNI add-on test which shows IAM role annotated

![Screenshot 2021-12-15 at 15 43 46](https://user-images.githubusercontent.com/19464259/146218767-de00fd45-4928-4cc8-b3d2-5e46c0e76250.png)

**Comment by milosh3411** [comment]
Tested, it is fine. Annotations in place. Thanks @vara-bonthu

**Comment by milosh3411** [comment]
Issue solved in Hotfix vpc cni #107
